#ifndef GUI_ICONS_H
#define GUI_ICONS_H

#include "launchelf.h"

typedef enum {
	GUI_ICON_DIR = 0,
	GUI_ICON_DIR_SYSTEM,
	GUI_ICON_FILE,
	GUI_ICON_FILE_ARCHIVE,
	GUI_ICON_FILE_ARCHIVE_SAS,
	GUI_ICON_FILE_EXECUTABLE_PS2,
	GUI_ICON_FILE_EXECUTABLE_WINDOWS,
	GUI_ICON_FILE_FONT,
	GUI_ICON_FILE_GAME_DISC,
	GUI_ICON_FILE_GAME_DISC_COMPRESSED,
	GUI_ICON_FILE_GAME_DISC_SHEET,
	GUI_ICON_FILE_GAME_DISK,
	GUI_ICON_FILE_GAME_FLOPPY,
	GUI_ICON_FILE_GAME_ROM,
	GUI_ICON_FILE_GAME_TAPE,
	GUI_ICON_FILE_ICON_PS2,
	GUI_ICON_FILE_LANGUAGE,
	GUI_ICON_FILE_MUSIC,
	GUI_ICON_FILE_PATCH,
	GUI_ICON_FILE_PICTURE,
	GUI_ICON_FILE_SAVE_OTHER,
	GUI_ICON_FILE_SAVE_PS1,
	GUI_ICON_FILE_SAVE_PS2,
	GUI_ICON_FILE_SCRIPT,
	GUI_ICON_FILE_SYSTEM,
	GUI_ICON_FILE_TEXT,
	GUI_ICON_FILE_VIDEO,
	GUI_ICON_FILE_VIDEO_SUBTITLES,
	GUI_ICON_FILE_VMC_OTHER,
	GUI_ICON_FILE_VMC_PS1,
	GUI_ICON_FILE_VMC_PS2,
	GUI_ICON_COUNT
} GuiIconId;

typedef struct {
	int iconbase;
	int color_id;
} GuiLegacyFontIcon;

const char *guiIconAssetName(GuiIconId icon_id);
GuiIconId guiIconForFileEntry(const char *path, const FILEINFO *file);
void guiIconPrimeDirectory(const char *path, const FILEINFO *files, int nfiles);
GuiLegacyFontIcon guiLegacyFontIconForGuiIcon(GuiIconId icon_id, int marked);

#endif
